### ISSUE TITLE
Project Detail Page

### ISSUE THREAD

**Issue by d4mation** [realbig/PL_MCG_PROJECT_PORTFOLIO_CPT#3]
1. Link to return to project listing page
2. Project Title - 40pt, Playfair Display Googlefont, #3651a7
3. Featured Image - 100% width. After responsive break; 95% width, centered
4. Project Long Description - Open field allows for typical WordPress content management
5. Button - When clicked, takes viewer to the Contact Us page.

![image](https://user-images.githubusercontent.com/7770631/28211308-eed053be-6869-11e7-9e4a-034cba6e2221.png)

**Comment by d4mation** [comment]
@BigActual should the Detail Page not have the Featured Image Banner/Hero? Currently the Featured Image is used there by the Theme, but it looks like the Featured Image should be placed at 2 in the image.

![image](https://user-images.githubusercontent.com/7770631/28280319-61fbd168-6af1-11e7-808f-8967033131c0.png)

**Comment by d4mation** [comment]
Also, what's with this Widget Area...? It doesn't seem to be part of the current site. Should this be added for the Project Single and Archive?

![image](https://user-images.githubusercontent.com/7770631/28283988-9b4a869c-6afd-11e7-9e5e-87b71eae963a.png)

**Comment by d4mation** [comment]
This is fully implemented outside of the Featured Image potential confusion and whatever the Widget Area(?) at the bottom of the page is.

**Comment by BigActual** [comment]
yes

Thanks,


Steven R. Bennett, Partner
Real Big Marketing, LLC.
(517)358-6794

--------------------------------------------

THIS MESSAGE IS CONFIDENTIAL. This e-mail message and any attachments are
proprietary and confidential information intended only for the use of the
recipient(s) named above. If you are not the intended recipient, you may
not print, distribute, or copy this message or any attachments. If you have
received this communication in error, please notify the sender by return
e-mail and delete this message and any attachments from your computer.



On Jul 17, 2017 2:38 PM, "Eric Defore" <notifications@github.com> wrote:

Also, what's with this Widget Area...? It doesn't seem to be part of the
current site. Should this be added for the Project Single and Archive?

[image: image]
<https://user-images.githubusercontent.com/7770631/28283988-9b4a869c-6afd-11e7-9e5e-87b71eae963a.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/realbig/PL_MCG_PROJECT_PORTFOLIO_CPT/issues/3#issuecomment-315843569>,
or mute the thread

**Comment by d4mation** [comment]
What is the Widget Area(?) supposed to be? Just 4 Sidebar/Widget areas that can have anything added to them?

**Comment by BigActual** [comment]
I see text only; Title and body copy. There are five of them by the way

**Comment by d4mation** [comment]
So, they're Widget Areas? To me they look like Nav Menus you'd see in a Footer.

**Comment by d4mation** [comment]
Added them as Widget Areas. I figure that _anything_ can go there that way.
